/**
 * Copyright (c) 2021 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.

 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/

 * SPDX-License-Identifier: EPL-2.0

 * Contributors:
 *  Broadcom, Inc. - initial API and implementation
 */

export const Theia = {
  addValueSettings: '.preference-array-element',
  body: 'body',
  bottomContentPanel: '#theia-bottom-content-panel',
  bottomSplitPanel: '#theia-bottom-split-panel',
  changeSettingsButton: '.theia-button[data-action="Change settings"]',
  consoleVariable: '.theia-debug-console-variable',
  clearItem: '.preference-array-clear-item',
  closeButton: '.fa.fa-times.closeButton',
  collapsed: '.theia-mod-collapsed',
  currentLine: '.current-line',
  currentTab: '#theia-main-content-panel .theia-app-main .p-TabBar-content .p-TabBar-tab.p-mod-current',
  debugBreakpointHint: '.codicon.theia-debug-breakpoint-hint',
  debugBreakpointInput: '.theia-debug-breakpoint-input',
  debugBreakpointSelect: '.theia-debug-breakpoint-select select',
  debugBreakpointWidget: '.zone-widget-container.theia-debug-breakpoint-widget',
  debugBreakpointsView: '[id*="debug:view-container"][id*="debug:breakpoints"]',
  debugBreakpont: '.codicon.theia-debug-breakpoint',
  debugConsloleExpression: '.theia-debug-console-expression',
  debugConsoleVariable: '.theia-debug-console-variable',
  debugContinue: '[id^="debug:toolbar"] .debug-action.theia-debug-continue',
  debugFrames: '[id*="debug:view-container"][id*="debug:frames"]',
  debugHighlightLine: '.theia-debug-top-stack-frame-line',
  debugIcon: '#shell-tab-debug',
  debugMode: 'body.theia-mod-debugging',
  debugRemoveAllBreakpoint: '#debug\\.breakpoint\\.removeAll',
  debugRestart: '[id^="debug:toolbar"] .debug-action.theia-debug-restart',
  debugStart: '[id^="debug"] .debug-action.theia-debug-start',
  debugStatementTrace: '[id*="debug:view-container"][id*="plugin-view:statementTrace"]',
  debugStepInto: '[id^="debug:toolbar"] .debug-action.theia-debug-step-into',
  debugStepOut: '[id^="debug:toolbar"] .debug-action.theia-debug-step-out',
  debugStepOver: '[id^="debug:toolbar"] .debug-action.theia-debug-step-over',
  debugStop: '[id^="debug:toolbar"] .debug-action.theia-debug-stop',
  debugVariablesPanel: '[id*="debug:view-container"][id*="debug:variables"]',
  dialogContent: '.dialogContent',
  dialogControl: '.dialogControl',
  dialogInput: 'div.dialogBlock input.theia-input',
  dialogTitle: '.dialogTitle',
  documentation: '.monaco-scrollable-element .docs',
  editor: '.theia-editor',
  editorError: '.squiggly-error',
  editorInfo: '.squiggly-info',
  editorWarn: '.squiggly-warning',
  elementCollapsed: '#theia-left-content-panel.theia-mod-collapsed',
  explorerIcon: 'ul.p-TabBar-content li#shell-tab-explorer-view-container',
  explorerId: '#explorer-view-container.p-mod-hidden',
  explorerView: '#explorer-view-container--files #files div.theia-TreeNodeContent',
  formatDocument: '[data-command="editor.action.formatDocument"]',
  goToDefinition: '[data-command="editor.action.revealDefinition"]',
  goToReference: '[data-command="editor.action.goToReferences"]',
  hoverOverContent: 'div.monaco-editor-hover-content',
  inputF1: '.quick-open-input input',
  langFeatures: '.pref-content-container.array',
  languageMode: '.right.area .hasCommand[title="Select Language Mode"]',
  leftRightPanel: '#theia-left-right-split-panel',
  lineNumber: '.line-numbers',
  lineContent: '.view-line',
  linesContent: '.view-lines',
  loadSpinner: '.left.area .element .fa-spin',
  mainContentPanel: '#theia-main-content-panel',
  menuBar: '[id="theia:menubar"]',
  menuBarContent: '.p-MenuBar-content',
  menuContent: '.p-Menu-content',
  modCurrent: 'p-mod-current',
  modHidden: '.p-mod-hidden',
  modToggled: 'p-mod-toggled',
  notification: 'theia-notification-list-item',
  notificationList: '.theia-notification-list',
  notificationMessage: '.theia-notification-message',
  notificationsContainer: '.theia-notifications-container',
  openTree: '.quick-open-tree',
  outlineView: '#outline-view',
  outlineViewTab: '#shell-tab-outline-view',
  outputChannelList: '#outputChannelList',
  outputContents: '#outputContents',
  peekViewWidget: '.peekview-widget .monaco-editor',
  popUpMsg: '.theia-notification-list-item-content',
  preLoad: 'div.theia-preload',
  referenceWidget: '.zone-widget',
  searchSettings: 'input.settings-search-input.theia-input',
  selectDebugConfiguration: '.theia-select.debug-configuration',
  slidePanelTitile: '.theia-sidepanel-title',
  subMenu: '[data-type="submenu"]',
  submenuItemLabel: '.p-Menu-itemLabel',
  suggestWidget: '[widgetid="editor.widget.suggestWidget"]',
  symbolHighlight: '.view-overlays .symbolHighlight',
  tabBar: '.p-TabBar',
  tabCloseButton: '.p-TabBar-tabCloseIcon',
  tabOpened: '[id^="shell-tab-code-editor-opener"]',
  theiConsoleInput: '.p-Widget .theia-console-input',
  theiaButton: 'theia-button',
  theiaButtonDontSave: '.theia-button.secondary',
  theiaButtonOK: '.theia-button.main',
  theiaClearConsole: '#debug\\.console\\.clear',
  theiaConsole: '.theia-console-ansi-console-item',
  treeContainer: '.theia-TreeContainer',
  treeNodeSegment: '.theia-TreeNodeSegment',
  treeViewDescription: '.theia-tree-view-description',
  typeALineNumber: 'input[title^="Type a line number"]',
  viewRulers: '.view-rulers',
  widgetMenu: '.p-Widget.p-Menu',
  workspaceTabInSettings: '.p-TabBar-tab.preferences-scope-tab',
  zoneWidget: '.zone-widget',
  quickFix: '.action span[title^="Quick Fix"]',
};

export const VSCODE = {
  dialogInput: 'div.dialogBlock input.theia-input',
  mainContentPanel: 'body',
  preLoad: '',
  leftRightPanel: '.split-view-container',
  elementCollapsed: '.menubar.compact.inactive',
  explorerIcon: '.action-label.codicon.codicon-explorer-view-icon',
  explorerView: '.part.sidebar.left',
  languageMode: '[id="status.editor.mode"]',
  typeALineNumber: '.quick-input-box',
  lineNumber: '.line-numbers',
  currentLine: '.current-line',
  goToDefinition: '[data-command="editor.action.revealDefinition"]',
  peekViewWidget: '.peekview-widget .monaco-editor',
  hoverOverContent: 'div.monaco-hover-content',
  editorError: '.squiggly-error',
  formatDocument: '[data-command="editor.action.formatDocument"]',
  currentTab: '.tabs-container .tab',
  tabCloseButton: '[title="Close (Ctrl+F4)"]',
  tabOpened: '[id^="shell-tab-code-editor-opener"]',
  editorInfo: '.squiggly-info',
  editorWarn: '.squiggly-warning',
  buttonDontSave: '[title="Don\'t Save"]',
  dialogContent: '.dialog-message-text',
  dialogControl: '.dialog-buttons-row',
  button: '.monaco-button.monaco-text-button',
  lineContent: '.view-line',
  linesContent: '.view-lines',
  treeContainer: '.pane-body.outline-pane',
  outLine: '[title="Outline"]',
  outlineMsg: '.outline-message',
  documentation: '.monaco-scrollable-element .docs',
  suggestWidget: '[widgetid="editor.widget.suggestWidget"]',
  outlineViewTab: '[aria-label="Outline Section"]',
  outlineView: '.outline-pane',
  modCurrent: '.expanded',
  treeNodeSegment: '.theia-TreeNodeSegment',
};

export const COBOLLS = {
  addCopybookInSettingsDNS: '#cobol-lsp\\.cpy-manager\\.paths-dsn-editor .preference-array-element-btn.add-btn',
  addCopybookInSettingsLocal: '#cobol-lsp\\.cpy-manager\\.paths-local-editor .preference-array-element-btn.add-btn',
  checkCopybookInSettingsDSN: '#cobol-lsp\\.cpy-manager\\.paths-dsn-editor .preference-array-element-val',
  checkCopybookInSettingsLocal: '#cobol-lsp\\.cpy-manager\\.paths-local-editor .pref-input',
  inputCopybookNameInSettingsDSN: '#cobol-lsp\\.cpy-manager\\.paths-dsn-editor .preference-array-input',
  inputCopybookNameInSettingsLocal: '#cobol-lsp\\.cpy-manager\\.paths-local-editor .preference-array-input',
  inputProfileInSettings: 'input[data-preference-id="cobol-lsp.cpy-manager.profiles"]',
  pathsDsnEditor: '#cobol-lsp\\.cpy-manager\\.paths-dsn-editor',
  pathsLocalEditor: '#cobol-lsp\\.cpy-manager\\.paths-local-editor',
  profilesEditor: '#cobol-lsp\\.cpy-manager\\.profiles-editor',
};

export const AA4MF = {
  addDataset: '[title*="Add dataset"]',
  addProtsym: '[data-command="__plugin.menu.action.symdump.addProtsym:0"]',
  deleteConnection: '[data-command="__plugin.menu.action.symdump.deleteConnection"]',
  deleteDataset: '[data-command="__plugin.menu.action.symdump.deleteDataset"]',
  deletereport: '[data-command*="__plugin.menu.action.symdump.deleteReport"]',
  displayGlobalOptions: '[data-command="__plugin.menu.action.symdump.displayGlobalOptions"]',
  displayProtdmpOptions: '[data-command="__plugin.menu.action.symdump.displayProtdmpOptions"]',
  displayReportOptions: '[data-command="__plugin.menu.action.symdump.displayReportOptions"]',
  editConnection: '[data-command*="__plugin.menu.action.symdump.editConnection"]',
  editDataset: '[data-command="__plugin.menu.action.symdump.editDataset"]',
  filterReports: '[data-command="__plugin.menu.action.symdump.filterDumps:0"]',
  filterReportsCancel: '[data-command="__plugin.menu.action.symdump.filterDumpsCancel:0"]',
  loadReports: '[data-command="__plugin.menu.action.symdump.loadDumps"]',
  lockReport: '[data-command="__plugin.menu.action.symdump.lockReport"]',
  newConnection: '[id="__plugin-view-container:symdumpView_title:__plugin.view.title.action.symdump.newConnection"]',
  sortReports: '[data-command="__plugin.menu.action.symdump.sortDumps"]',
  sortreportAscending: '[data-command="__plugin.menu.action.symdump.sortDumpsAscending"]',
  sortreportDescending: '[data-command="__plugin.menu.action.symdump.sortDumpsDescending"]',
  symdumpId: '[id="symdump"]',
  symdumpJob: '[id="Job=${jobName}${param}"]',
  symdumpPanel: '[id="plugin-view-container:symdumpView"]',
  symdumpView: 'ul.p-TabBar-content li[id="shell-tab-plugin-view-container:symdumpView"]',
  unlockReport: '[data-command="__plugin.menu.action.symdump.unlockReport"',
  viewLabel: '[data-pref-id="symdump.view.label"]',
  viewLabelEditor: '[id="symdump.view.label-editor"]',
};

export const E4E = {
  editElement: '[data-command="__plugin.menu.action.e4e.editElement"]',
  endevorExplorer: '[id="plugin-view:endevorExplorer"]',
  explorerContainer: '.p-TabBar-tab[id="shell-tab-plugin-view-container:e4eExplorerContainer"]',
  elmTreeView: '[id="plugin-view:e4e.elmTreeView"]',
  hideServise: '[data-command="__plugin.menu.action.e4e.hideService"]',
  pluginView: '[id="plugin-view-container:e4eExplorerContainer--plugin-view:e4e.elmTreeView"]',
  retrieveElementWithDependencies: '[data-command="__plugin.menu.action.e4e.retrieveElementWithDependencies"]',
};

export const ZOWE = {
  addSession: '#__plugin\\.view\\.title\\.action\\.zowe\\.addSession',
  deleteProfile: '[data-command*="__plugin.menu.action.zowe.deleteProfile"]',
  zoweJobs: '[id*="plugin-view-container:zowe--plugin-view:zowe.jobs"]',
  zoweTreeContainer: '[id*="plugin-view:zowe.explorer"] .theia-TreeContainer',
  zoweHidden: '#plugin-view-container\\:zowe.p-mod-hidden',
  zoweView: '.p-TabBar-content #shell-tab-plugin-view-container\\:zowe',
  zowePluginView: '[id*="plugin-view-container:zowe"][id*="plugin-view:zowe.explorer"]',
};
